language: python
python:
    - "2.7"
    - "3.1"
    - "3.2"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - pip install -r requirements.txt
    - pip install coveralls

script:
    - py.test

after_success:
    - coveralls
